include("build/debug/conanbuildinfo.premake.lua")
package_assimp_debug_libdirs = conan_libdirs_assimp
package_assimp_debug_links = conan_libs_assimp
package_bullet_debug_libdirs = conan_libdirs_bullet3
package_bullet_debug_links = conan_libs_bullet3
package_fmt_debug_libdirs = conan_libdirs_fmt
package_fmt_debug_links = conan_libs_fmt
package_freetype_debug_libdirs = conan_libdirs_freetype
package_freetype_debug_links = conan_libs_freetype
package_rttr_debug_libdirs = conan_libdirs_rttr
package_rttr_debug_links = conan_libs_rttr

include("build/release/conanbuildinfo.premake.lua")
package_assimp_release_libdirs = conan_libdirs_assimp
package_assimp_release_links = conan_libs_assimp
package_bullet_release_libdirs = conan_libdirs_bullet3
package_bullet_release_links = conan_libs_bullet3
package_fmt_release_libdirs = conan_libdirs_fmt
package_fmt_release_links = conan_libs_fmt
package_freetype_release_libdirs = conan_libdirs_freetype
package_freetype_release_links = conan_libs_freetype
package_rttr_release_libdirs = conan_libdirs_rttr
package_rttr_release_links = conan_libs_rttr

package_assimp_includedirs = conan_includedirs_assimp
package_bullet_includedirs = conan_includedirs_bullet3
package_fmt_includedirs = conan_includedirs_fmt
package_freetype_includedirs = conan_includedirs_freetype
package_nlohmann_includedirs = conan_includedirs_nlohmann_json
package_rttr_includedirs = conan_includedirs_rttr
package_stb_includedirs = conan_includedirs_stb